menu:
    Blog: /
    About: javascript:alert("Hey there. I'm an engineer and music producer. Moving images, graphics, communication and sound is my main focus.")
    Archive: /archives/
    Email: javascript:alert("You'd like to establish contact? Reach me via disparat (ät) gmail.com. Looking forward :)")
    Code: https://github.com/tchakabam
    
    Music: https://soundcloud.com/tchakabam
    Photos: https://www.flickr.com/photos/tchakabam/albums

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:
cloudTie:

# Analytics
# google-analytics:
#ga: UA-65933410-1

# Copyright Infomation
startyear: 2017
